language: cpp
os: windows
install:
    - cmake --version
script:
    - cd mlp
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
    - ctest -V -C Debug
after_failure:
    - cat "${TRAVIS_BUILD_DIR}/build/CMakeFiles/CMakeOutput.log"
